-intstyle "ise" -incremental -lib "unisims_ver" -lib "unimacro_ver" -lib "xilinxcorelib_ver" -o "/home/this/mux/mux4_tb_isim_beh.exe" -prj "/home/this/mux/mux4_tb_beh.prj" "work.mux4_tb" "work.glbl" 
